[project]
name = "sorobun-translator"
version = "0.1.0"
description = ""
authors = [
    {name = "kwadraten",email = "ne1hr7s4@addy.to"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kuzu>=0.9.0",
    "mecab-python3>=1.0.10",
    "openai>=1.75.0",
]
